management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
#spring.cloud.config.enabled=false
management.endpoints.web.exposure.include=health,metrics
management.health.circuitbreakers.enabled=true

# Critical: This must be true for each instance or the default config
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
